#!/bin/bash
killall mbsync 2>/dev/null
xrandr --output HDMI1 --off
pacmd set-sink-port 0 analog-output-speaker
sleep 2
for W in $(seq 1 10); do
  i3-msg "workspace $W; move workspace to output eDP1"
done
